version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run: echo 1 # TODO:TEST
  deploy:
    working_directory: ~/app
    docker:
      - image: google/cloud-sdk:217.0.0-alpine
    steps:
      - checkout
      - run: apk add --no-cache nodejs npm yarn
      - run: npm install
      - run: npm run build
      - run: echo $GCLOUD_SERVICE_KEY > ${HOME}/gcloud-service-key.json
      - run: gcloud auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
      - run: gcloud app deploy --quiet --project $GCP_PROJECT_ID

workflows:
  version: 2
  main:
    jobs:
#      - build # TODO:TESTTEST
      - deploy:
          filters:
            branches:
              only: master
